{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: easyauth
  namespace: {{.Values.namespace}}
  labels:
    linkerd.io/extension: easyauth
    component: easyauth-injector
    {{- with .Values.pdb.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.pdb.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable | default 0 }}
  {{- end }}
  selector:
    matchLabels:
      component: easyauth-injector
{{- end }}
